config/routes.rb
Rails.application.routes.draw do
  resources :troops
  resources :categories
  resources :abouts
  resources :infos
  resources :date_shows
  get 'sport_shows/index'
  get 'admin/index'
  resources :sport_shows
  get '/admin/sport_shows', to: 'sport_shows#index'
  namespace :admin do
    root "admin#index"
    resources :sport_shows, as: 'admin_sport_shows'
  end
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/date_show.rb
class DateShow < ApplicationRecord

  validates :sport_show_id, presence: true
  belongs_to :sport_show

end

app/controllers/date_shows_controller.rb
class DateShowsController < ApplicationController
  before_action :set_date_show, only: [:show, :edit, :update, :destroy]

  # GET /date_shows
  # GET /date_shows.json
  def index
    @date_shows = DateShow.includes(:sport_show).all
  end

  # GET /date_shows/1
  # GET /date_shows/1.json
  def show
  end

  # GET /date_shows/new
  def new
    @date_show = DateShow.new
    @sport_shows = SportShow.all
  end

  # GET /date_shows/1/edit
  def edit
    @date_shows = DateShow.all
    @sport_shows = SportShow.all
  end

  # POST /date_shows
  # POST /date_shows.json
  def create
    @date_show = DateShow.new(date_show_params)

    respond_to do |format|
      if @date_show.save
        format.html { redirect_to @date_show, notice: 'Date show was successfully created.' }
        format.json { render :show, status: :created, location: @date_show }
      else
        format.html { render :new }
        format.json { render json: @date_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /date_shows/1
  # PATCH/PUT /date_shows/1.json
  def update
    respond_to do |format|
      if @date_show.update(date_show_params)
        format.html { redirect_to @date_show, notice: 'Date show was successfully updated.' }
        format.json { render :show, status: :ok, location: @date_show }
      else
        format.html { render :edit }
        format.json { render json: @date_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /date_shows/1
  # DELETE /date_shows/1.json
  def destroy
    @date_show.destroy
    respond_to do |format|
      format.html { redirect_to date_shows_url, notice: 'Date show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_date_show
      @date_show = DateShow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def date_show_params
      params.require(:date_show).permit(:date, :sport_show_id)
    end
end

app/views/date_shows/_form.html.erb
<%= simple_form_for(@date_show) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :sport_show_id, collection: @sport_shows %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/date_shows/edit.html.erb
<h1>Editing Date Show</h1>

<%= render 'form', date_show: @date_show %>

<%= link_to 'Show', @date_show %> |
<%= link_to 'Back', date_shows_path %>

app/views/date_shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Date Shows</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @date_shows.each do |date_show| %>
      <tr>
        <td scope="row"><%= date_show.date %></td>
        <td scope="row"><%= date_show.sport_show.name %></td>
        <td><%= link_to 'Show', date_show %></td>
        <td><%= link_to 'Edit', edit_date_show_path(date_show) %></td>
        <td><%= link_to 'Destroy', date_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Date Show', new_date_show_path %>

app/views/date_shows/new.html.erb
<h1>New Date Show</h1>

<%= render 'form', date_show: @date_show %>

<%= link_to 'Back', date_shows_path %>

app/views/date_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @date_show.date %>
</p>

<%= link_to 'Edit', edit_date_show_path(@date_show) %> |
<%= link_to 'Back', date_shows_path %>