config/routes.rb
Rails.application.routes.draw do
  resources :troops
  resources :categories
  resources :abouts
  resources :infos
  resources :date_shows
  get 'sport_shows/index'
  get 'admin/index'
  resources :sport_shows
  get '/admin/sport_shows', to: 'sport_shows#index'
  namespace :admin do
    root "admin#index"
    resources :sport_shows, as: 'admin_sport_shows'
  end
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/troop.rb
class Troop < ApplicationRecord
  validates :name, :description, :picture, :slug, :category_id, :sport_show_id, presence: true
  belongs_to :category
  belongs_to :sport_show
end

app/controllers/troops_controller.rb
class TroopsController < ApplicationController
  before_action :set_troop, only: [:show, :edit, :update, :destroy]

  # GET /troops
  # GET /troops.json
  def index
    @troops = Troop.includes(:sport_show, :category).all
  end

  # GET /troops/1
  # GET /troops/1.json
  def show
  end

  # GET /troops/new
  def new
    @troop = Troop.new
    @categories = Category.all
    @sportShows = SportShow.all
  end

  # GET /troops/1/edit
  def edit
    @categories = Category.all
    @sportShows = SportShow.all
  end

  # POST /troops
  # POST /troops.json
  def create
    @troop = Troop.new(troop_params)

    respond_to do |format|
      if @troop.save
        format.html { redirect_to @troop, notice: 'Troop was successfully created.' }
        format.json { render :show, status: :created, location: @troop }
      else
        format.html { render :new }
        format.json { render json: @troop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /troops/1
  # PATCH/PUT /troops/1.json
  def update
    respond_to do |format|
      if @troop.update(troop_params)
        format.html { redirect_to @troop, notice: 'Troop was successfully updated.' }
        format.json { render :show, status: :ok, location: @troop }
      else
        format.html { render :edit }
        format.json { render json: @troop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /troops/1
  # DELETE /troops/1.json
  def destroy
    @troop.destroy
    respond_to do |format|
      format.html { redirect_to troops_url, notice: 'Troop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_troop
      @troop = Troop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def troop_params
      params.require(:troop).permit(:name, :picture, :description, :slug, :category_id, :sport_show_id)
    end
end

app/views/troops/_form.html.erb
<%= simple_form_for(@troop) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :picture %>
    <%= f.input :description %>
    <%= f.input :slug %>
    <%= f.input :category_id, collection: @categories %>
    <%= f.input :sport_show_id, collection: @sportShows %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/troops/edit.html.erb
<h1>Editing Troop</h1>

<%= render 'form', troop: @troop %>

<%= link_to 'Show', @troop %> |
<%= link_to 'Back', troops_path %>

app/views/troops/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>
  <%= link_to 'sport shows', sport_shows_index_url %>
</p>
<p>
  <%= link_to 'date shows', date_shows_url %>
</p>
<p>
  <%= link_to 'categories', categories_url %>
</p>
  <h1>Troops</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Catégorie</th>
        <th scope="col">Show</th>
        <th scope="col">Picture</th>
        <th scope="col">Description</th>
        <th scope="col">Slug</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @troops.each do |troop| %>
        <tr>
          <td scope="row"><%= troop.name %></td>
          <td><%= troop.category.name %></td>
          <td><%= troop.sport_show.name %></td>
          <td><%= troop.picture %></td>
          <td><%= troop.description %></td>
          <td><%= troop.slug %></td>
          <td><%= link_to 'Show', troop %></td>
          <td><%= link_to 'Edit', edit_troop_path(troop) %></td>
          <td><%= link_to 'Destroy', troop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Troop', new_troop_path %>
</div>

app/views/troops/new.html.erb
<div class="container">
  <h1>New Troop</h1>

  <%= render 'form', troop: @troop %>

  <%= link_to 'Back', troops_path %>
</div>

app/views/troops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @troop.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @troop.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @troop.description %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @troop.slug %>
</p>

<%= link_to 'Edit', edit_troop_path(@troop) %> |
<%= link_to 'Back', troops_path %>